### ISSUE TITLE
OS X version

### ISSUE THREAD

**Issue by beeb** [AgentFeeble/pgoapi#1]
Hey, thanks for providing your api open source. I wanted to have a go at it today but quickly realized the pod is meant for iOS. Anyway you could make an OS X version? From looking at the code, there is very few iOS specific instructions so it should be quite easy to do.

I tried copying manually all the files into my OS X project but I'm struggling to make it work with all the imports and objective-C stuff.

Cheers

**Comment by AgentFeeble** [comment]
Right-O. I had to set the deployment target to 10.10 for OSX, because that's whats required by `ProtocolBuffers-Swift`, but I've tested, and it should be ready to go.

**Comment by beeb** [comment]
Amazing! I actually did it myself during the last couple of hours haha, took some trial and error but it's working now. Thanks for the rest of the world though!

**Comment by AgentFeeble** [comment]
No problem 👍
