### ISSUE TITLE
encryptMethod undefined for architecture x86_64

### ISSUE THREAD

**Issue by beeb** [AgentFeeble/pgoapi#5]
Hey, thanks a lot for updating the API so fast, I must admit I wasn't expecting it so soon.

Got a small compilation issue when trying to replicate the example. `encryptMethod` defined in `encrypt.h` is not found anywhere and leads to a failed build.

Am I missing something, maybe a file that's missing from the podspec and that I didn't get by updating?

**Comment by AgentFeeble** [comment]
Hello there

The missing file contains copyrighted code, so unfortunately I can't include it in the repo. Last time I checked there were a few people hosting `encrypt.c` on github, it may still be up. If you can't find it, there's also a pre-compiled `encrypt.so` for a few different platforms out there. You can also have a look at the [Pokemon Go Dev subreddit](www.reddit.com/r/pokemongodev). 

If you use the `encrypt.so`, the encrypt method may have a different signature, so you would have to update `encrypt.h` and the method invocation in `Encrypt.swift`
