### ISSUE TITLE
apiUrl

### ISSUE THREAD

**Issue by 0x2400** [AgentFeeble/pgoapi#8]
"apiUrl: pgorelease.nianticlabs.com/plfe/35 "

35?

**Comment by AgentFeeble** [comment]
Not sure what your question is... 

When accessing the API for the first time, the 'https://pgorelease.nianticlabs.com/plfe/rpc' endpoint is used. The response of this API call contains the endpoint to be used for subsequent API calls, and this is the URL you're seeing.
